[package]
name = "ssg-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
tera = "1"

[[bin]]
name = "ssg-rust"
path = "main.rs"
