[package]
name = "ssg-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "1.1"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "ssg-rust"
path = "main.rs"
